# Generated by Django 5.1.3 on 2024-12-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='compleated',
            new_name='completed',
        ),
    ]
